name: release

on:
  workflow_dispatch

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '^1.3'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "github@lts.sh"
      - run: npm install
      - name: Version
        shell: bash
        run: npx nx affected --target=version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Tag last-release
        shell: bash
        run: |
          git tag -f latest-release
      - name: Push changes to master branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
